[smtp]
host = "smtp.gmail.com"
port = 465
security = "SSL"

[imap]
host = "imap.gmail.com"
port = 993
security = "SSL"

oidc_discovery_endpoint = "https://accounts.google.com/.well-known/openid-configuration"

scopes = [
  "openid",
  "https://mail.google.com/",
]
