name: Add Entry

on:
  issues:
    types:
      - closed

jobs:
  handle_issue:
    if: contains(github.event.issue.labels.*.name, 'provider-request')
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Extract info + write TOML
        run: |
          content=$(echo "${{ github.event.issue.body }}")
          provider=$(echo "$content" | awk '/### Provider/{getline; getline; print}')
          smtp_host=$(echo "$content" | awk '/### SMTP Host/{getline; getline; print}')
          smtp_port=$(echo "$content" | awk '/### SMTP Port/{getline; getline; print}')
          smtp_security=$(echo "$content" | awk '/### SMTP Security/{getline; getline; print}')
          imap_host=$(echo "$content" | awk '/### IMAP Host/{getline; getline; print}')
          imap_port=$(echo "$content" | awk '/### IMAP Port/{getline; getline; print}')
          imap_security=$(echo "$content" | awk '/### IMAP Security/{getline; getline; print}')
          oidc=$(echo "$content" | awk '/### OIDC Discovery Endpoint/{getline; getline; print}')

          mapfile -t scopes < <(
            echo "$content" |
            awk '
              /### Scopes/ {flag=1; next}
              /^### / {flag=0}
              flag && NF
            '
          )

          filename="providers/${provider}.toml"
          mkdir -p providers

          {
            echo "name = \"$provider\""
            echo
            echo "[smtp]"
            echo "host = \"$smtp_host\""
            echo "port = $smtp_port"
            echo "security = \"$smtp_security\""
            echo
            echo "[imap]"
            echo "host = \"$imap_host\""
            echo "port = $imap_port"
            echo "security = \"$imap_security\""
            echo
            echo "oidc_discovery_endpoint = \"$oidc\""
            echo
            echo "scopes = ["

            for scope in "${scopes[@]}"; do
              echo "  \"$scope\","
            done

            echo "]"
          } > "$filename"

          cat "$filename"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          git commit -m "Add provider entry" || echo "No changes"

          git push
